apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: otel
  namespace: istio-system
  finalizers:
    - opentelemetrycollector.opentelemetry.io/finalizer
spec:
  networkPolicy:
    enabled: false
  observability:
    metrics: {}
  deploymentUpdateStrategy: {}
  config:
    exporters:
      debug: {}
      otlp:
        endpoint: 'tempo-sample-distributor.istio-system.svc.cluster.local:4317'
        tls:
          insecure: true
      prometheus:
        endpoint: '0.0.0.0:8889'
        resource_to_telemetry_conversion:
          enabled: true
    processors:
      batch:
        send_batch_size: 10000
        timeout: 10s
      k8sattributes: {}
      memory_limiter:
        check_interval: 1s
        limit_percentage: 50
        spike_limit_percentage: 30
      resourcedetection:
        detectors:
          - openshift
    receivers:
      jaeger:
        protocols:
          grpc:
            endpoint: '0.0.0.0:14250'
          thrift_binary:
            endpoint: '0.0.0.0:6832'
          thrift_compact:
            endpoint: '0.0.0.0:6831'
          thrift_http:
            endpoint: '0.0.0.0:14268'
      k8s_cluster:
        collection_interval: 10s
        distribution: openshift
      opencensus: {}
      otlp:
        protocols:
          grpc:
            endpoint: '0.0.0.0:4317'
          http:
            endpoint: '0.0.0.0:4318'
      zipkin:
        endpoint: '0.0.0.0:9411'
    service:
      pipelines:
        logs/entity_events:
          exporters:
            - debug
          receivers:
            - k8s_cluster
        metrics:
          exporters:
            - prometheus
          receivers:
            - otlp
        traces:
          exporters:
            - otlp
          processors:
            - memory_limiter
            - k8sattributes
            - resourcedetection
            - batch
          receivers:
            - jaeger
            - opencensus
            - otlp
            - zipkin
      telemetry:
        metrics:
          readers:
            - pull:
                exporter:
                  prometheus:
                    host: 0.0.0.0
                    port: 8888
  mode: deployment
  resources: {}
  podDnsConfig: {}
  managementState: managed
  upgradeStrategy: automatic
  ingress:
    route: {}
  serviceAccount: otel-collector-deployment
  daemonSetUpdateStrategy: {}
  targetAllocator:
    allocationStrategy: consistent-hashing
    collectorNotReadyGracePeriod: 30s
    collectorTargetReloadInterval: 30s
    filterStrategy: relabel-config
    observability:
      metrics: {}
    prometheusCR:
      scrapeInterval: 30s
    resources: {}
  replicas: 1
  ipFamilyPolicy: SingleStack
  configVersions: 3
