apiVersion: tempo.grafana.com/v1alpha1
kind: TempoStack
metadata:
  name: sample
  namespace: istio-system
  finalizers:
    - tempo.grafana.com/finalizer
  labels:
    app.kubernetes.io/managed-by: tempo-operator
    tempo.grafana.com/distribution: openshift
spec:
  observability:
    grafana:
      instanceSelector: {}
    metrics: {}
    tracing:
      jaeger_agent_endpoint: 'localhost:6831'
      otlp_http_endpoint: 'http://localhost:4320'
  timeout: 30s
  resources:
    total:
      limits:
        cpu: '2'
        memory: 2Gi
  search:
    defaultResultLimit: 20
    maxDuration: 0s
  managementState: Managed
  limits:
    global:
      ingestion: {}
      query:
        maxSearchDuration: 0s
  serviceAccount: tempo-sample
  images: {}
  template:
    compactor:
      replicas: 1
    distributor:
      component:
        replicas: 1
      tls:
        enabled: false
    gateway:
      component:
        replicas: 1
      enabled: false
      ingress:
        route: {}
      rbac:
        enabled: false
    ingester:
      replicas: 1
      resources:
        claims:
          - name: alibaba
            request: ''
    querier:
      replicas: 1
    queryFrontend:
      component:
        replicas: 1
      jaegerQuery:
        authentication:
          enabled: true
          resources:
            claims:
              - name: tempo-claim
                request: ''
          sar: '{"namespace": "istio-system", "resource": "pods", "verb": "get"}'
        enabled: true
        ingress:
          route:
            termination: edge
          type: route
        monitorTab:
          enabled: false
          prometheusEndpoint: ''
        servicesQueryDuration: 72h0m0s
        tempoQuery: {}
  replicationFactor: 1
  storage:
    secret:
      name: cloud-credentials
      type: s3
    tls:
      enabled: false
  storageSize: 1Gi
  hashRing:
    memberlist: {}
  retention:
    global:
      traces: 48h0m0s
